feature: adicionando data de nascimento em equipe e filtro de nascime…
toguvr/gabinete_front pull request #54
Opened 2023-04-08 19:47 UTC by Hugo-Pereira-98

…nto em equipe e eleitor

2023-04-08 20:55 UTC, toguvr requested changes

2023-04-08 20:55 UTC, toguvr commented on src/pages/Permission.tsx
> +                                new Date(permission?.user?.birthdate),
nao entendi o pq adiciona 12h?

2023-04-08 21:11 UTC, Hugo-Pereira-98 commented on src/pages/Permission.tsx
> +                                new Date(permission?.user?.birthdate),
Eu segui o padrao que voces estao usando em todas as paginas, o getFormatDate nao funciona direito passando só a string sem adicionar horas antes

2023-04-08 22:11 UTC, toguvr commented on src/pages/Permission.tsx
> +                                new Date(permission?.user?.birthdate),
ta doidao, devemos estar usando isso na hora de enviar pro back e nao te mostrar em tela, aqui n faz sentido, vai somar 12 vai virar o outro dia po

2023-04-10 00:42 UTC, toguvr approved these changes

2023-04-10 00:43 UTC, merged